### ISSUE TITLE
Erreur traduction "cell" ?

### ISSUE THREAD

**Issue by elliotfontaine** [boubl/Aseprite-French-Translation#2]
`frame_cel_properties = Propriétés du Ce&llulo...`
`frame_duplicate_cels = &Dupliquer le/les Cellulo(s)`
`frame_duplicate_linked_cels = Dupliquer le/les cellulo(s) &associé(s)`

Cellule plutôt que Cellulo ?

**Comment by boubl** [comment]
Merci pour cette remarque!
C'est cool que des personnes osent enfin me donner leur avis sur la traduction.

[Cellulo, ou Celluloïd](https://fr.wikipedia.org/wiki/Cellulo%C3%AFd_(dessin_anim%C3%A9)) est en fait un vrai terme utilisé dans l'animation. Il y a d'ailleurs un détail important, le mot ["cel"](https://en.wikipedia.org/wiki/Cel) ne possède qu'un L, et donc n'est pas la même chose que ["cell"](https://en.wikipedia.org/wiki/Cell_(biology)).

J'ai aussi fait la confusion dans les premières versions de la traduction, et j'ai remplacé par "cellulo" quand je me suis rendu compte de mon erreur (j'ai pas utilisé "celluloïd" parce que je trouvais ça moins beau que "cellulo"). Après, est-ce que "cellule" est vraiment plus compréhensible que "cellulo"? Je pense pas, mais si tu as des idées pour un autre mot qui serait plus évocateur de sa fonction, n'hésite pas.

**Comment by elliotfontaine** [comment]
> Merci pour cette remarque! C'est cool que des personnes osent enfin me donner leur avis sur la traduction.
> 
> [Cellulo, ou Celluloïd](https://fr.wikipedia.org/wiki/Cellulo%C3%AFd_(dessin_anim%C3%A9)) est en fait un vrai terme utilisé dans l'animation. Il y a d'ailleurs un détail important, le mot ["cel"](https://en.wikipedia.org/wiki/Cel) ne possède qu'un L, et donc n'est pas la même chose que ["cell"](https://en.wikipedia.org/wiki/Cell_(biology)).
> 
> J'ai aussi fait la confusion dans les premières versions de la traduction, et j'ai remplacé par "cellulo" quand je me suis rendu compte de mon erreur (j'ai pas utilisé "celluloïd" parce que je trouvais ça moins beau que "cellulo"). Après, est-ce que "cellule" est vraiment plus compréhensible que "cellulo"? Je pense pas, mais si tu as des idées pour un autre mot qui serait plus évocateur de sa fonction, n'hésite pas.

Globalement la traduction est très bonne!

Ha oui bien vu pour cel VS cell. Je ne connaissait pas.

Peut-être que "cello" ou "celluloïd" sont plus parlants? Comme ça les ignares comme moi comprendront qu'il ne s'agit pas d'une typo, mais bien d'autre chose.
