### ISSUE TITLE
May be the incorrect translation? `deleting_tilemaps_will_delete_tilesets`

### ISSUE THREAD

**Issue by TakWolf** [boubl/Aseprite-French-Translation#5]
https://github.com/boubl/Aseprite-French-Translation/blob/master/fr.ini#L68

https://github.com/aseprite/aseprite/pull/4156/files

**Comment by boubl** [comment]
Thanks, fixed in [fdf352b](https://github.com/boubl/Aseprite-French-Translation/commit/fdf352b0631ad0f55040bce572ccf40aa142aa34)
